name: Build On MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
        build_type: [Release]
        include:
          - os: macos-12
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install Dependencies 
        run: |
          brew install ninja

      - name: Create Build Directory
        run: mkdir -p build

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/bins

      - name: Build
        run: cmake --build build

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: built-executable-${{ matrix.os }}
          path: bins/
